# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/waveform_gui',
                'doc_host': 'https://conorkeogh.github.io',
                'git_url': 'https://github.com/conorkeogh/waveform_gui',
                'lib_path': 'waveform_gui'},
  'syms': {'waveform_gui.core': {'waveform_gui.core.foo': ('core.html#foo', 'waveform_gui/core.py')}}}
